# Generated by Django 4.2.3 on 2023-07-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioVenta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='fechaCreacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
